### ISSUE TITLE
On non 16:9 screens I can't see the game verison. (Mobile)

### ISSUE THREAD

**Issue by Dim999YT** [NeoNyaa/Geode-ShowGameVersion#1]
![Screenshot_2024-11-30-20-14-53-987_com.geode.launcher.jpg](https://github.com/user-attachments/assets/9f803f6c-1e89-4833-8e61-f1d8464a5fc7)

**Comment by NeoNyaa** [comment]
unless im mistaken I can see it in the top left corner

**Comment by NeoNyaa** [comment]
If it is cutting off and the screenshot doesn't clearly indicate _where_ it's cutting off, can you give me some more information, such as if it's partly cut off or if it's completely outside the view of the screen.

**Comment by NeoNyaa** [comment]
If I don't get a response within the next 4 days, I will close the issue as stale.
Reason being, it should not take 1 week to get back to me after I enquire about something.

**Comment by NeoNyaa** [comment]
Closed as stale: No response with a week of initial opening

**Comment by NeoNyaa** [comment]
Closed as stale: No response with a week of initial opening
